package com.ganesh.mahindra.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.ganesh.mahindra.model.BreakdownYearly;
@Repository
public interface BreakdownYearlyRepository extends JpaRepository<BreakdownYearly, Integer>{

	/*@Query(value="select count(*) as breakdown_count,year(date)as year from why_why_f18 where machine_id=:machinId and month between :fromMonth and :toMonth group by year",nativeQuery=true)
	List<BreakdownYearly> getYearwiseBreakdowns(@Param("machinId")int machinId,@Param("fromMonth") String fromMonth,@Param("toMonth") String toMonth);
*/
	//@Query(value="select SUM(1) as id,coalesce((select count(*) as breakdown_count1 from why_why_f18 where bd_ms_pt='MS' and dept=:deptId and date between :fromFirstYear and :toFirstYear ),0) as first_year, coalesce((select count(*) as breakdown_count2 from why_why_f18 where bd_ms_pt='MS' and dept=:deptId and date between :fromSecondYear and :toSecondYear ),0) as second_year, coalesce((select count(*) as breakdown_count3 from why_why_f18 where bd_ms_pt='MS' and dept=:deptId and date between :fromThirdYear and :toThirdYear ),0) as third_year, coalesce((select count(*) as breakdown_count4 from why_why_f18 where bd_ms_pt='MS' and dept=:deptId and date between :fromFourthYear and :toFourthYear ),0) as fourth_year from why_why_f18",nativeQuery=true)
    @Query(value="\n" + 
    		"select SUM(1) as id,coalesce((CASE WHEN (coalesce((select count(*) as breakdown_count1 from why_why_f18 where bd_ms_pt='MS' and dept=:deptId and date between :fromFirstYear and :toFirstYear ),0)<=0) THEN (select ex_string from mac_breakdown_target where graph_type=1 and status=1 and ex_int=:deptId and year=:fromFirst) else  (coalesce((select count(*) as breakdown_count1 from why_why_f18 where bd_ms_pt='MS' and dept=:deptId and date between :fromFirstYear and :toFirstYear ),0))  END),0) as first_year,Coalesce((CASE WHEN (coalesce((select count(*) as breakdown_count2 from why_why_f18 where bd_ms_pt='MS' and dept=:deptId and date between :fromSecondYear and :toSecondYear ),0) <=0) THEN (select ex_string from mac_breakdown_target where graph_type=1 and status=1 and ex_int=:deptId and year=:fromSecond) else (coalesce((select count(*) as breakdown_count2 from why_why_f18 where bd_ms_pt='MS' and dept=:deptId and date between :fromSecondYear and :toSecondYear ),0)) END),0) as second_year,coalesce((CASE WHEN (coalesce((select count(*) as breakdown_count3 from why_why_f18 where bd_ms_pt='MS' and dept=:deptId and date between :fromThirdYear and :toThirdYear ),0)<=0) THEN (select ex_string from mac_breakdown_target where graph_type=1 and status=1 and ex_int=:deptId and year=:fromThird) else  (coalesce((select count(*) as breakdown_count3 from why_why_f18 where bd_ms_pt='MS' and dept=:deptId and date between :fromThirdYear and :toThirdYear ),0)) END),0) as third_year,coalesce((CASE WHEN (coalesce((select count(*) as breakdown_count4 from why_why_f18 where bd_ms_pt='MS' and dept=:deptId and date between :fromFourthYear and :toFourthYear ),0)<=0) THEN (select ex_string from mac_breakdown_target where graph_type=1 and status=1 and ex_int=:deptId and year=:fromFourth) else (coalesce((select count(*) as breakdown_count4 from why_why_f18 where bd_ms_pt='MS' and dept=:deptId and date between :fromFourthYear and :toFourthYear ),0)) END ),0) as fourth_year from why_why_f18",nativeQuery=true)
	BreakdownYearly getYearwiseBreakdowns(@Param("fromFirst") String fromFirst,@Param("fromSecond") String fromSecond,@Param("fromThird") String fromThird,@Param("fromFourth") String fromFourth,@Param("fromFirstYear") String fromFirstYear,@Param("toFirstYear") String toFirstYear,
			@Param("fromSecondYear")String fromSecondYear,@Param("toSecondYear") String toSecondYear, @Param("fromThirdYear")String fromThirdYear,@Param("toThirdYear") String toThirdYear,@Param("fromFourthYear") String fromFourthYear,
			@Param("toFourthYear")String toFourthYear ,@Param("deptId")int deptId);

	//@Query(value="select SUM(1) as id,coalesce((select count(*) as breakdown_count1 from why_why_f18 where bd_ms_pt='BD' and dept=:deptId and rank=1 and date between :fromFirstYear and :toFirstYear ),0) as first_year, coalesce((select count(*) as breakdown_count2 from why_why_f18 where bd_ms_pt='BD' and rank=1 and dept=:deptId and date between :fromSecondYear and :toSecondYear ),0) as second_year, coalesce((select count(*) as breakdown_count3 from why_why_f18 where bd_ms_pt='BD' and rank=1 and dept=:deptId and date between :fromThirdYear and :toThirdYear ),0) as third_year, coalesce((select count(*) as breakdown_count4 from why_why_f18 where bd_ms_pt='BD' and rank=1 and dept=:deptId and date between :fromFourthYear and :toFourthYear ),0) as fourth_year from why_why_f18",nativeQuery=true)
	@Query(value="select SUM(1) as id,coalesce((CASE WHEN (coalesce((select count(*) as breakdown_count1 from why_why_f18 where bd_ms_pt='BD' and dept=:deptId and rank=1 and date between :fromFirstYear and :toFirstYear ),0)<=0) THEN (select ex_string from mac_breakdown_target where graph_type=2 and status=1 and ex_int=:deptId and year=:fromFirst) else (coalesce((select count(*) as breakdown_count1 from why_why_f18 where bd_ms_pt='BD' and dept=:deptId and rank=1 and date between :fromFirstYear and :toFirstYear ),0)) END),0) as first_year, coalesce((CASE WHEN (coalesce((select count(*) as breakdown_count2 from why_why_f18 where bd_ms_pt='BD' and rank=1 and dept=:deptId and date between :fromSecondYear and :toSecondYear ),0)<=0) THEN (select ex_string from mac_breakdown_target where graph_type=2 and status=1 and ex_int=:deptId and year=:fromSecond) else (coalesce((select count(*) as breakdown_count2 from why_why_f18 where bd_ms_pt='BD' and rank=1 and dept=:deptId and date between :fromSecondYear and :toSecondYear ),0)) END),0) as second_year, coalesce((CASE WHEN (coalesce((select count(*) as breakdown_count3 from why_why_f18 where bd_ms_pt='BD' and rank=1 and dept=:deptId and date between :fromThirdYear and :toThirdYear ),0)<=0) THEN (select ex_string from mac_breakdown_target where graph_type=2 and status=1 and ex_int=:deptId and year=:fromThird) else (coalesce((select count(*) as breakdown_count3 from why_why_f18 where bd_ms_pt='BD' and rank=1 and dept=:deptId and date between :fromThirdYear and :toThirdYear ),0)) END),0) as third_year, coalesce((CASE WHEN (coalesce((select count(*) as breakdown_count4 from why_why_f18 where bd_ms_pt='BD' and rank=1 and dept=:deptId and date between :fromFourthYear and :toFourthYear ),0)<=0) THEN (select ex_string from mac_breakdown_target where graph_type=2 and status=1 and ex_int=:deptId and year=:fromFourth) else (coalesce((select count(*) as breakdown_count4 from why_why_f18 where bd_ms_pt='BD' and rank=1 and dept=:deptId and date between :fromFourthYear and :toFourthYear ),0)) END),0)  as fourth_year from why_why_f18",nativeQuery=true)
    BreakdownYearly getARankYearwiseBreakdowns(@Param("fromFirst") String fromFirst,@Param("fromSecond") String fromSecond,@Param("fromThird") String fromThird,@Param("fromFourth") String fromFourth,@Param("fromFirstYear") String fromFirstYear,@Param("toFirstYear") String toFirstYear,
			@Param("fromSecondYear")String fromSecondYear,@Param("toSecondYear") String toSecondYear, @Param("fromThirdYear")String fromThirdYear,@Param("toThirdYear") String toThirdYear,@Param("fromFourthYear") String fromFourthYear,
			@Param("toFourthYear")String toFourthYear,@Param("deptId")int deptId);

	//@Query(value="select SUM(1) as id,coalesce((select count(*) as breakdown_count1 from why_why_f18 where bd_ms_pt='BD' and rank!=1 and dept=:deptId and date between :fromFirstYear and :toFirstYear ),0) as first_year, coalesce((select count(*) as breakdown_count2 from why_why_f18 where bd_ms_pt='BD' and rank!=1 and dept=:deptId and date between :fromSecondYear and :toSecondYear ),0) as second_year, coalesce((select count(*) as breakdown_count3 from why_why_f18 where bd_ms_pt='BD' and rank!=1 and dept=:deptId and date between :fromThirdYear and :toThirdYear ),0) as third_year, coalesce((select count(*) as breakdown_count4 from why_why_f18 where bd_ms_pt='BD' and rank!=1 and dept=:deptId and date between :fromFourthYear and :toFourthYear ),0) as fourth_year from why_why_f18",nativeQuery=true)
	@Query(value="select SUM(1) as id,coalesce((CASE WHEN (coalesce((select count(*) as breakdown_count1 from why_why_f18 where bd_ms_pt='BD' and rank!=1 and dept=:deptId and date between :fromFirstYear and :toFirstYear ),0)<=0) THEN (select ex_string from mac_breakdown_target where graph_type=3 and status=1 and ex_int=:deptId and year=:fromFirst) else (coalesce((select count(*) as breakdown_count1 from why_why_f18 where bd_ms_pt='BD' and rank!=1 and dept=:deptId and date between :fromFirstYear and :toFirstYear ),0)) END),0) as first_year, coalesce((CASE WHEN (coalesce((select count(*) as breakdown_count2 from why_why_f18 where bd_ms_pt='BD' and rank!=1 and dept=:deptId and date between :fromSecondYear and :toSecondYear ),0) <=0) THEN (select ex_string from mac_breakdown_target where graph_type=3 and status=1 and ex_int=:deptId and year=:fromSecond) else (coalesce((select count(*) as breakdown_count2 from why_why_f18 where bd_ms_pt='BD' and rank!=1 and dept=:deptId and date between :fromSecondYear and :toSecondYear ),0) ) END),0) as second_year,coalesce((CASE WHEN (coalesce((select count(*) as breakdown_count3 from why_why_f18 where bd_ms_pt='BD' and rank!=1 and dept=:deptId and date between :fromThirdYear and :toThirdYear ),0)<=0) THEN (select ex_string from mac_breakdown_target where graph_type=3 and status=1 and ex_int=:deptId and year=:fromThird) else (coalesce((select count(*) as breakdown_count3 from why_why_f18 where bd_ms_pt='BD' and rank!=1 and dept=:deptId and date between :fromThirdYear and :toThirdYear ),0)) END),0) as third_year, coalesce((CASE WHEN (coalesce((select count(*) as breakdown_count4 from why_why_f18 where bd_ms_pt='BD' and rank!=1 and dept=:deptId and date between :fromFourthYear and :toFourthYear ),0)<=0) THEN (select ex_string from mac_breakdown_target where graph_type=3 and status=1 and ex_int=:deptId and year=:fromFourth) else (coalesce((select count(*) as breakdown_count4 from why_why_f18 where bd_ms_pt='BD' and rank!=1 and dept=:deptId and date between :fromFourthYear and :toFourthYear ),0)) END),0) as fourth_year from why_why_f18",nativeQuery=true)
	BreakdownYearly getAllBrekYearwiseBreakdowns(@Param("fromFirst") String fromFirst,@Param("fromSecond") String fromSecond,@Param("fromThird") String fromThird,@Param("fromFourth") String fromFourth,@Param("fromFirstYear") String fromFirstYear,@Param("toFirstYear") String toFirstYear,
			@Param("fromSecondYear")String fromSecondYear,@Param("toSecondYear") String toSecondYear, @Param("fromThirdYear")String fromThirdYear,@Param("toThirdYear") String toThirdYear,@Param("fromFourthYear") String fromFourthYear,
			@Param("toFourthYear")String toFourthYear,@Param("deptId")int deptId);

	@Query(value="select SUM(1) as id,coalesce((select ex_string from mac_breakdown_target where graph_type=:graphType and ex_int=:deptId and year=:fromSecond and status=1),0)as first_year,coalesce((select ex_string from mac_breakdown_target where graph_type=:graphType and ex_int=:deptId and year=:fromThird and status=1),0)as second_year,coalesce((select ex_string from mac_breakdown_target where graph_type=:graphType and ex_int=:deptId and year=:fromFourth and status=1),0)as third_year,coalesce((select ex_string from mac_breakdown_target where graph_type=:graphType and ex_int=:deptId and year=:year and status=1),0)as fourth_year from dual",nativeQuery=true)
	BreakdownYearly getPreviousActualSchedule(@Param("graphType")int graphType,@Param("fromSecond") int fromSecond,@Param("fromThird") int fromThird,@Param("fromFourth") int fromFourth,@Param("year") int year,
			@Param("deptId")int deptId);
}
