package com.ganesh.mahindra.repository;


import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.ganesh.mahindra.model.BreakdownMonthwise;
@Repository
public interface BreakdownMonthwiseRepository extends JpaRepository<BreakdownMonthwise, Integer>{

	@Query(value="select SUM(1) as id,coalesce((select count(*) from why_why_f18 where bd_ms_pt='MS' and  month=:first and dept=:deptId),0) as  breakdown_cnt1,coalesce((select count(*) from why_why_f18 where  bd_ms_pt='MS' and month=:second and dept=:deptId),0) as  breakdown_cnt2,coalesce((select count(*) from why_why_f18 where bd_ms_pt='MS' and month=:third and dept=:deptId),0) as  breakdown_cnt3,coalesce((select count(*) from why_why_f18 where bd_ms_pt='MS' and month=:fourth and dept=:deptId),0) as  breakdown_cnt4,coalesce((select count(*) from why_why_f18 where bd_ms_pt='MS' and month=:fifth and dept=:deptId),0) as  breakdown_cnt5,coalesce((select count(*) from why_why_f18 where bd_ms_pt='MS' and month=:sixth and dept=:deptId),0) as  breakdown_cnt6,coalesce((select count(*) from why_why_f18 where bd_ms_pt='MS' and month=:seventh and dept=:deptId),0) as  breakdown_cnt7,coalesce((select count(*) from why_why_f18 where bd_ms_pt='MS' and month=:eighth and dept=:deptId),0) as  breakdown_cnt8,coalesce((select count(*) from why_why_f18 where bd_ms_pt='MS' and month=:ninth and dept=:deptId),0) as  breakdown_cnt9,coalesce((select count(*) from why_why_f18 where bd_ms_pt='MS' and month=:tenth and dept=:deptId),0) as  breakdown_cnt10,coalesce((select count(*) from why_why_f18 where bd_ms_pt='MS' and month=:eleventh and dept=:deptId),0) as  breakdown_cnt11,coalesce((select count(*) from why_why_f18 where bd_ms_pt='MS' and month=:twelvth and dept=:deptId),0) as  breakdown_cnt12 from why_why_f18",nativeQuery=true)
	BreakdownMonthwise getMonthwiseBreakdowns(@Param("first")String first,@Param("second")String second,@Param("third")String third,@Param("fourth")String fourth,@Param("fifth")String fifth,@Param("sixth")String sixth,@Param("seventh")String seventh,@Param("eighth")String eighth,@Param("ninth")String ninth,@Param("tenth")String tenth,@Param("eleventh")String eleventh,@Param("twelvth")String twelvth,@Param("deptId")int deptId);

	@Query(value="select SUM(1) as id,coalesce((select count(*) from why_why_f18 where bd_ms_pt='BD' and rank=1 and month=:first and dept=:deptId),0) as  breakdown_cnt1,coalesce((select count(*) from why_why_f18 where bd_ms_pt='BD' and rank=1 and month=:second and dept=:deptId),0) as  breakdown_cnt2,coalesce((select count(*) from why_why_f18 where bd_ms_pt='BD' and rank=1 and month=:third and dept=:deptId),0) as  breakdown_cnt3,coalesce((select count(*) from why_why_f18 where bd_ms_pt='BD' and rank=1 and month=:fourth and dept=:deptId),0) as  breakdown_cnt4,coalesce((select count(*) from why_why_f18 where bd_ms_pt='BD' and rank=1 and month=:fifth and dept=:deptId),0) as  breakdown_cnt5,coalesce((select count(*) from why_why_f18 where bd_ms_pt='BD' and rank=1 and month=:sixth and dept=:deptId),0) as  breakdown_cnt6,coalesce((select count(*) from why_why_f18 where bd_ms_pt='BD' and rank=1 and month=:seventh and dept=:deptId),0) as  breakdown_cnt7,coalesce((select count(*) from why_why_f18 where bd_ms_pt='BD' and rank=1 and month=:eighth and dept=:deptId),0) as  breakdown_cnt8,coalesce((select count(*) from why_why_f18 where bd_ms_pt='BD' and rank=1 and month=:ninth and dept=:deptId),0) as  breakdown_cnt9,coalesce((select count(*) from why_why_f18 where bd_ms_pt='BD' and rank=1 and month=:tenth and dept=:deptId),0) as  breakdown_cnt10,coalesce((select count(*) from why_why_f18 where bd_ms_pt='BD' and rank=1 and month=:eleventh and dept=:deptId),0) as  breakdown_cnt11,coalesce((select count(*) from why_why_f18 where bd_ms_pt='BD' and rank=1 and month=:twelvth and dept=:deptId),0) as  breakdown_cnt12 from why_why_f18",nativeQuery=true)
	BreakdownMonthwise getARankMonthwiseBreakdowns(@Param("first")String first,@Param("second")String second,@Param("third")String third,@Param("fourth")String fourth,@Param("fifth")String fifth,@Param("sixth")String sixth,@Param("seventh")String seventh,@Param("eighth")String eighth,@Param("ninth")String ninth,@Param("tenth")String tenth,@Param("eleventh")String eleventh,@Param("twelvth")String twelvth,@Param("deptId")int deptId);

	@Query(value="select SUM(1) as id,coalesce((select count(*) from why_why_f18 where bd_ms_pt='BD' and rank!=1 and month=:first and dept=:deptId),0) as  breakdown_cnt1,coalesce((select count(*) from why_why_f18 where bd_ms_pt='BD' and rank!=1 and month=:second and dept=:deptId),0) as  breakdown_cnt2,coalesce((select count(*) from why_why_f18 where bd_ms_pt='BD' and rank!=1 and month=:third and dept=:deptId),0) as  breakdown_cnt3,coalesce((select count(*) from why_why_f18 where bd_ms_pt='BD' and rank!=1 and month=:fourth and dept=:deptId),0) as  breakdown_cnt4,coalesce((select count(*) from why_why_f18 where bd_ms_pt='BD' and rank!=1 and month=:fifth and dept=:deptId),0) as  breakdown_cnt5,coalesce((select count(*) from why_why_f18 where bd_ms_pt='BD' and rank!=1 and month=:sixth and dept=:deptId),0) as  breakdown_cnt6,coalesce((select count(*) from why_why_f18 where bd_ms_pt='BD' and rank!=1 and month=:seventh and dept=:deptId),0) as  breakdown_cnt7,coalesce((select count(*) from why_why_f18 where bd_ms_pt='BD' and rank!=1 and month=:eighth and dept=:deptId),0) as  breakdown_cnt8,coalesce((select count(*) from why_why_f18 where bd_ms_pt='BD' and rank!=1 and month=:ninth and dept=:deptId),0) as  breakdown_cnt9,coalesce((select count(*) from why_why_f18 where bd_ms_pt='BD' and rank!=1 and month=:tenth and dept=:deptId),0) as  breakdown_cnt10,coalesce((select count(*) from why_why_f18 where bd_ms_pt='BD' and rank!=1 and month=:eleventh and dept=:deptId),0) as  breakdown_cnt11,coalesce((select count(*) from why_why_f18 where bd_ms_pt='BD' and rank!=1 and month=:twelvth and dept=:deptId),0) as  breakdown_cnt12 from why_why_f18",nativeQuery=true)
	BreakdownMonthwise getAllBrekMonthwiseBreakdowns(@Param("first")String first,@Param("second")String second,@Param("third")String third,@Param("fourth")String fourth,@Param("fifth")String fifth,@Param("sixth")String sixth,@Param("seventh")String seventh,@Param("eighth")String eighth,@Param("ninth")String ninth,@Param("tenth")String tenth,@Param("eleventh")String eleventh,@Param("twelvth")String twelvth,@Param("deptId")int deptId);



	/*@Query(value="select SUM(1) as id,coalesce((select month_target from mac_breakdown_target where  year=:fromYear and month=4),0) as breakdown_cnt1,coalesce((select month_target from mac_breakdown_target where  year=:fromYear and month=5),0) as breakdown_cnt2,coalesce((select month_target from mac_breakdown_target where  year=:fromYear and month=6),0) as breakdown_cnt3,coalesce((select month_target from mac_breakdown_target where  year=:fromYear and month=7),0) as breakdown_cnt4,coalesce((select month_target from mac_breakdown_target where  year=:fromYear and month=8),0) as breakdown_cnt5,coalesce((select month_target from mac_breakdown_target where  year=:fromYear and month=9),0) as breakdown_cnt6,coalesce((select month_target from mac_breakdown_target where  year=:fromYear and month=10),0) as breakdown_cnt7,coalesce((select month_target from mac_breakdown_target where  year=:fromYear and month=11),0) as breakdown_cnt8,coalesce((select month_target from mac_breakdown_target where  year=:fromYear and month=12),0) as breakdown_cnt9,coalesce((select month_target from mac_breakdown_target where  year=:toYear and month=01),0) as breakdown_cnt10,coalesce((select month_target from mac_breakdown_target where  year=:toYear and month=02),0) as breakdown_cnt11,coalesce((select month_target from mac_breakdown_target where  year=:toYear and month=03),0) as breakdown_cnt12 from mac_breakdown_target",nativeQuery=true)
	BreakdownMonthwise getMonthwiseL5Target(@Param("fromYear") int fromYear,@Param("toYear") int toYear);
*/
}
